/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import Layout from '@/components/Layout';

export default function Notes() {
  const [teachers, setTeachers] = useState([]); const [id, setId] = useState(''); const [notes, setNotes] = useState([]); const [note, setNote] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch('/api/teachers').then((response) => response.json()).then((data) => setTeachers(data.teachers || [])).catch(() => setTeachers([])); }, []);
  async function loadNotes() { if (!id) return setNotes([]); const data = await fetch(`/api/teacher-notes?teacherId=${encodeURIComponent(id)}`).then((response) => response.json()); setNotes(data.notes || []); }
  useEffect(() => { loadNotes(); }, [id]);
  async function addNote() { if (!id || !note.trim()) return; setSaving(true); try { const response = await fetch('/api/teacher-notes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ teacher_id: id, note: note.trim() }) }); if (!response.ok) throw new Error(); setNote(''); await loadNotes(); } finally { setSaving(false); } }
  return <Layout title={<div className="flex items-center gap-1"><Link href="/dashboard" aria-label="Back to Dashboard" className="flex h-7 w-7 items-center justify-center text-slate-800"><ArrowLeft size={20} /></Link><span> Notes</span></div>}><section className="card mx-auto max-w-3xl p-5 sm:p-6"><h2 className="m-0 text-lg font-bold">Teacher Notes</h2><p className="mt-1 text-sm text-slate-500">Add and view notes for a specific teacher.</p><label className="mt-5 block"><span className="label">Select Teacher</span><select className="field" value={id} onChange={(event) => setId(event.target.value)}><option value="">Select Teacher</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.full_name || 'Unnamed teacher'}</option>)}</select></label>{id && <><label className="mt-5 block"><span className="label">Add Note</span><textarea className="field min-h-[110px] resize-none" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add a note regarding this teacher..." /></label><button type="button" className="btn-primary mt-3" disabled={saving || !note.trim()} onClick={addNote}>{saving ? 'Saving...' : 'Add Note'}</button><div className="mt-7"><h3 className="m-0 text-base font-bold">Previous Notes</h3>{notes.length ? <div className="mt-3 space-y-3">{notes.map((entry) => <article key={entry.id} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="m-0 text-xs font-semibold text-slate-500">{new Date(entry.created_at).toLocaleDateString('en-IN')}</p><p className="mb-0 mt-2 whitespace-pre-wrap text-sm text-slate-700">{entry.note}</p></article>)}</div> : <p className="mt-3 text-sm text-slate-500">No notes added for this teacher yet.</p>}</div></>}</section></Layout>;
}
